package clase3;

public class Humano {
	
	protected final static int cantidadOjos = 2; //ATRIBUTO DE CLASE
	//REVISAR PERO: PROTECTED = PUEDE ACCEDERSE SOLO A OBJETOS DE ESTA CLASE.
	// FINAL - NO PUEDE CAMBIAR SU VALOR (SINO PODRIA CAMBIARSE EN LAS ISNTANCIAS, MAS ALLA DE QUE UNA VEZ QUE LO CAMBIAS EN LA INSTANCIA, SE CAMBIA EN TODO)
	// STATIC - NO ES NECESARIO INSTANCIAR PARA USARLO. SE LLAMA DIRECTAMENTE A LA CLASE Y SU ATRIBUTO

}
